version: '3.4'

services:
  web:
    build:
      context: .
      # dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes: 
      - .:/app
    command: >
      sh -c "python manage.py 0.0.0.0:8000"